services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    # Volúmenes para persistencia de datos
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    ports:
      - "35:53/tcp"
      - "35:53/udp"
      - "81:80/tcp"
      - "446:443/tcp"
      - "446:443/udp"
      - "3005:3000/tcp" # Puerto para la configuración inicial
    # Opcional: Si quieres que use la IP de tu red local directamente
    # network_mode: "host"